config/routes.rb
Rails.application.routes.draw do



  resources :mobiles
  get '/' => 'mobiles#index'
  get 'mobiles/:id' => 'mobiles#show' , as: :mobile_path
  get 'mobiles/new' => 'mobiles#new'
  post 'mobiles/index' => 'mobiles#create'
  get 'mobiles/:id/edit' => 'mobiles#edit', as: :edit_path
  patch 'mobiles/:id' => 'mobiles#update'
  get 'mobiles/:id/destroy' => 'mobiles#destroy', as: :delete_path

  get 'signup' => 'users#new'
  resources :users

  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'



  get 'orders/index' => 'orders#index'
  get 'orders/new' => 'orders#new'
  post 'orders/index' => 'orders#create'
  get 'orders/:id/destroy' => 'orders#destroy', as: :delete_order
  resources :orders
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mobile.rb
class Mobile < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  def admin?
    self.role == 'admin'
  end

  def user?
    self.role == 'user'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/login' unless current_user.user?
  end

  def require_admin
    redirect_to '/login' unless current_user.admin?
  end

end

app/controllers/mobiles_controller.rb
class MobilesController < ApplicationController

  before_action :require_admin, only: [:edit,:new,:update,:create,:destroy]

  def index
    @mobiles = Mobile.all
  end

 def show
   @mobile = Mobile.find(params[:id])
 end

  def edit
    @mobile = Mobile.find(params[:id])
  end

  def new
    @mobile = Mobile.new
  end

  def update
    @mobile = Mobile.find(params[:id])
    if @mobile.update(mobile_params)
      redirect_to @mobile
    else
      render 'edit'
    end

  end


  def create
    @mobile = Mobile.new(mobile_params)
    if @mobile.save
      redirect_to @mobile, :notice => "Uspesno dodato"
    else
      render 'new'

    end
  end


  def destroy
    @mobile = Mobile.find(params[:id])
    @mobile.destroy
    redirect_to '/'
  end

  private
  def mobile_params
    params.require(:mobile).permit(:ime, :slika, :opis, :specifikacije)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :require_admin, only: [:destroy,:index]
  before_action :require_user, only: [:new,:create]

  def index
    @orders = Order.all
  end

  def new
    @order = Order.new
  end

  def create
  @order = Order.new(order_params)
  if @order.save
    redirect_to '/'
  else
    render 'new'

  end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to '/orders/index'
  end
  private
  def order_params
    params.require(:order).permit(:user,:pitanje)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to 'login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :role, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mobiles_helper.rb
module MobilesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MobileSh</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'default', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mobiles/create.html.erb
<h1>Mobiles#create</h1>
<p>Find me in app/views/mobiles/create.html.erb</p>

app/views/mobiles/destroy.html.erb
<h1>Mobiles#destroy</h1>
<p>Find me in app/views/mobiles/destroy.html.erb</p>

app/views/mobiles/edit.html.erb
<html>

<head>

  <title>Mobile Shop</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


  <style>
      body {
          font-family: 'Roboto', sans-serif;
          font-weight: 300;
      }

      header {
          padding: 20px 0;

      }


      footer .row {
          display: flex;
          align-items: center;
      }

      header .row {
          display: flex;
          align-items: center;

      }
      header h1 {
          font-weight: 700;
          margin: 0;
      }

      header nav {
          display: flex;
          justify-content: flex-end;

      }

      header p {
          padding: 0 20px;
          margin: 0;
      }


      .create {
          margin: 40px 0;
      }

      .messages a,
      .create .actions input {
          background-color: #0084d7;
          border: none;
          color: #fff;
          cursor: pointer;
          font-size: 14px;
          margin-top: 10px;
          padding: 12px 24px;
          transition: background-color 0.5s;
          text-decoration: none;
          display: inline-block;
      }



      p.time {
          color: #0084d7;
          font-size: 12px;
          margin-top: 12px;
      }

      button {
          background-color: #f2580b;
          border: none;
          color: #fff;
          cursor: pointer;
          font-size: 14px;
          margin-top: 10px;
          padding: 12px 24px;
          transition: background-color 0.5s;
      }

      button:hover {
          background-color: #c24609;
          transition: background-color 0.5s;
      }

      form label {
          display: block;
          width: 100%;
      }

      form textarea {
          border: 1px solid gray;
          font-family: 'Roboto', sans-serif;
          font-size: 14px;
          font-weight: 300;
          margin: 20px 0 10px;
          min-height: 100px;
          padding: 16px;
          transition: border 0.5s;
          width: 100%;

      }



      form textarea:focus {
          border: 1px solid #0084d7;
          box-shadow: 0;
          outline: 0;
          transition: border 0.5s;
      }




  </style>
</head>

<body>
<header class="containter">
  <div class="row">
    <h1 class="col-xs-4">Mobile Shop</h1>
    <nav class="col-xs-8 text-right">
      <% if !current_user %>
          <p><%= link_to "Početna", '/' %></p>
          <p><%= link_to "LogIn", '/login' %></p>
          <p><%= link_to "SignUp", '/signup' %></p>


      <% else %>
          <p><%= current_user.email %></p>
          <p><%= link_to "Početna", '/' %></p>
          <p><%= link_to "Logout", logout_path, method: "delete" %> </p>

      <% end %>
      <% if current_user && current_user.admin? %>
          <p><%= link_to "Poruke", '/orders/index' %></p>
          <p><%= link_to "Dodaj", '/mobiles/new' %></p>
      <% end %>
      <% if current_user && current_user.user? %>
          <p><%= link_to "Kontakt", 'orders/new' %></p>
      <% end %>
    </nav>
  </div>
</header>


<div class="create">
  <div class="container">
    <%= form_for(@mobile) do |f| %>
        <div class="field">
          <p>Naziv telefona</p>
          <%= f.text_area :ime %><br>
          <p>Slika</p>
          <%= f.text_area :slika %><br>
          <p>Model</p>
          <%= f.text_area :opis %>
          <p>Specifikacije</p>
          <%= f.text_area :specifikacije %>
        </div>
        <div class="actions">
          <%= f.submit "Ažuriraj" %>
        </div>
    <% end %>
  </div>
</div>


</body>


</html>

app/views/mobiles/index.html.erb
<!DOCTYPE html>
<html>

            <head>

              <title>Mobile Shop</title>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
              <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
              <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


              <style>
                  body {
                      font-family: 'Roboto', sans-serif;
                      font-weight: 300;
                  }

                  header {
                      padding: 20px 0;

                  }

                  header .row,
                  footer .row {
                      display: flex;
                      align-items: center;
                  }

                  header h1 {
                      font-weight: 700;
                      margin: 0;

                  }

                  header nav {
                      display: flex;
                      justify-content: flex-end;
                      position: fixed;
                  }

                  header p {
                      padding: 0 20px;
                      margin: 0;
                  }
                  .jumbotron {
                      display: flex;
                      align-items: center;
                      background-image: url('https://cdn.theconversation.com/files/85948/width1356x668/image-20150622-17765-1y007h7.jpg');
                      background-size: cover;
                      color: #ffffff;
                      height: 500px;
                      text-shadow: 0.25px 0.25px 0.25px #000000;
                  }

                  .jumbotron h2 {
                      font-size: 90px;
                      font-weight: 700;
                      margin: 0;
                      color: white;
                      background-color:rgba(167,207,219,0.7);


                  }

                  .card {
                      color: black;
                      display: block;
                      margin: 4px 0;

                  }

                  .tags .card h2 {
                      color: black;
                      position: absolute;
                      left: 0;
                      right: 0;
                      text-align: center;
                      top: 25%;
                  }


                  .tags img,
                  .tag img {
                      display:block;
                      width:100% \9;
                      max-width:90px;
                      height: 90px;
                  }

                  .tag h2, .tag .card h2, .destination h2, .destination p {
                      padding: 0 20px 0;
                  }

                  .tag .card p {
                      color: #0f0f0f;
                      font-size: 14px;
                      font-weight: 300;
                      -webkit-box-orient: vertical;
                      padding: 0 20px 20px;
                  }
                  .natpis h1 {
                      text-align: center;
                      font-family: 'Roboto' sans-serif;
                      padding: 20px 0;
                      border-bottom: 1px solid black;
                  }

              </style>
            </head>

            <body>
            <header class="containter">

              <div class="row">
                <h1 class="col-xs-4">Mobile Shop</h1>
                <nav class="col-xs-8 text-right">
                  <% if !current_user %>
                      <p><%= link_to "Početna", '/' %></p>
                      <p><%= link_to "LogIn", '/login' %></p>
                      <p><%= link_to "SignUp", '/signup' %></p>


                  <% else %>
                      <p><%= current_user.email %></p>
                      <p><%= link_to "Početna", '/' %></p>
                      <p><%= link_to "Logout", logout_path, method: "delete" %> </p>

                  <% end %>
                  <% if current_user && current_user.admin? %>
                      <p><%= link_to "Poruke", '/orders/index' %></p>
                      <p><%= link_to "Dodaj", '/mobiles/new' %></p>
                  <% end %>
                  <% if current_user && current_user.user? %>
                      <p><%= link_to "Kontakt", 'orders/new' %></p>
                  <% end %>
                </nav>
              </div>
            </header>
            <section class="jumbotron">
              <div class="container">
                <div class="row text-center">
                  <h2>Dobrodošli u MobileShop</h2>
                </div>
              </div>

            </section>

            <div class="tag">
              <div class="container">
                <div class="natpis">
                  <h1 class="col-xs-12">Trenutno u ponudi</h1>
                </div>
                <div class="cards row">
                  <% @mobiles.each do |t| %>
                      <div class="card col-xs-2">
                        <h1><%= t.ime %></h1>
                        <%= image_tag t.slika %>
                        <h3><%= t.opis %></h3>

                        <%= link_to "Više", mobile_path_path(t) %>

                      </div>
                  <% end %>
                </div>

              </div>
            </div>


            </body>


            </html>

app/views/mobiles/new.html.erb
<html>

<head>

  <title>Mobile Shop</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


  <style>
      body {
          font-family: 'Roboto', sans-serif;
          font-weight: 300;
      }

      header {
          padding: 20px 0;

      }


      footer .row {
          display: flex;
          align-items: center;
      }

      header .row {
          display: flex;
          align-items: center;

      }
      header h1 {
          font-weight: 700;
          margin: 0;
      }

      header nav {
          display: flex;
          justify-content: flex-end;

      }

      header p {
          padding: 0 20px;
          margin: 0;
      }


      .create {
          margin: 40px 0;
      }

      .messages a,
      .create .actions input {
          background-color: #0084d7;
          border: none;
          color: #fff;
          cursor: pointer;
          font-size: 14px;
          margin-top: 10px;
          padding: 12px 24px;
          transition: background-color 0.5s;
          text-decoration: none;
          display: inline-block;
      }



      p.time {
          color: #0084d7;
          font-size: 12px;
          margin-top: 12px;
      }

      button {
          background-color: #f2580b;
          border: none;
          color: #fff;
          cursor: pointer;
          font-size: 14px;
          margin-top: 10px;
          padding: 12px 24px;
          transition: background-color 0.5s;
      }

      button:hover {
          background-color: #c24609;
          transition: background-color 0.5s;
      }

      form label {
          display: block;
          width: 100%;
      }

      form textarea {
          border: 1px solid gray;
          font-family: 'Roboto', sans-serif;
          font-size: 14px;
          font-weight: 300;
          margin: 20px 0 10px;
          min-height: 100px;
          padding: 16px;
          transition: border 0.5s;
          width: 100%;

      }



      form textarea:focus {
          border: 1px solid #0084d7;
          box-shadow: 0;
          outline: 0;
          transition: border 0.5s;
      }




  </style>
</head>

<body>
<header class="containter">
  <div class="row">
    <h1 class="col-xs-4">Mobile Shop</h1>
    <nav class="col-xs-8 text-right">
      <% if !current_user %>
          <p><%= link_to "Početna", '/' %></p>
          <p><%= link_to "LogIn", '/login' %></p>
          <p><%= link_to "SignUp", '/signup' %></p>


      <% else %>
          <p><%= current_user.email %></p>
          <p><%= link_to "Početna", '/' %></p>
          <p><%= link_to "Logout", logout_path, method: "delete" %> </p>

      <% end %>
      <% if current_user && current_user.admin? %>
          <p><%= link_to "Poruke", '/orders/index' %></p>
          <p><%= link_to "Dodaj", 'mobiles/new' %></p>
      <% end %>
      <% if current_user && current_user.user? %>
          <p><%= link_to "Kontakt", 'orders/new' %></p>
      <% end %>
    </nav>
  </div>
</header>


<div class="create">
  <div class="container">
    <%= form_for(@mobile) do |f| %>
        <div class="field">
          <p>Naziv telefona</p>
          <%= f.text_area :ime %><br>
          <p>Slika</p>
          <%= f.text_area :slika %><br>
          <p>Model</p>
          <%= f.text_area :opis %>
          <p>Specifikacije</p>
          <%= f.text_area :specifikacije %>
        </div>
        <div class="actions">
          <%= f.submit "Dodaj" %>
        </div>
    <% end %>
  </div>
</div>


</body>


</html>

app/views/mobiles/show.html.erb
<!DOCTYPE html>
<html>

<head>

  <title>Mobile Shop</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


  <style>
      body {
          font-family: 'Roboto', sans-serif;
          font-weight: 300;
      }

      header {
          padding: 20px 0;
      }

      header .row,
      footer .row {
          display: flex;
          align-items: center;
      }

      header h1 {
          font-weight: 700;
          margin: 0;
      }

      header nav {
          display: flex;
          justify-content: flex-end;
      }

      header p {
          padding: 0 20px;
          margin: 0;
      }


      .card {
          color: black;
          display: block;
          margin: 4px 0;

      }

      .tags .card h2 {
          color: black;
          position: absolute;
          left: 0;
          right: 0;
          text-align: center;
          top: 25%;
      }

      .tags img,
      .tag img {
          display:block;
          width:100%;

          height: 100%;
      }

      .tag h2, .tag .card h2, .destination h2, .destination p {
          padding: 0 20px 0;
          display: block;
      }

      .tag .card p {
          color: #0f0f0f;
          font-size: 14px;
          font-weight: 300;
          -webkit-box-orient: vertical;
          padding: 0 20px 20px;
      }


  </style>
</head>

<body>

<header class="containter">

  <div class="row">
    <h1 class="col-xs-4">Mobile Shop</h1>
    <nav class="col-xs-8 text-right">
      <% if !current_user %>
          <p><%= link_to "Početna", '/' %></p>
          <p><%= link_to "LogIn", '/login' %></p>
          <p><%= link_to "SignUp", '/signup' %></p>


      <% else %>
          <p><%= current_user.email %></p>
          <p><%= link_to "Početna", '/' %></p>
          <p><%= link_to "Logout", logout_path, method: "delete" %> </p>

      <% end %>
      <% if current_user && current_user.admin? %>
          <p><%= link_to "Poruke", '/orders/index' %></p>
          <p><%= link_to "Dodaj", '/mobiles/new' %></p>
      <% end %>
      <% if current_user && current_user.user? %>
          <p><%= link_to "Kontakt", '/orders/new' %></p>
      <% end %>
    </nav>
  </div>

</header>


<div class="tag">
  <div class="container">
    <h2><%= @mobile.ime %> <%= @mobile.opis %></h2>

    <div class="cards row">

      <div class="card col-xs-12">
        <%= image_tag @mobile.slika %>

        <p><%= @mobile.specifikacije %></p>

        <% if current_user && current_user.admin? %>
        <%= button_to "Ažuriraj", edit_path_path(@mobile), method: :get, class: "btn btn-primary btn-block"  %> <br/>

                    <p>  <%= link_to "Brisanje",delete_path_path, method: "delete"  %>   </p>
                               <% end %>
            </div>

            </div>

            </div>
            </div>


            </body>


            </html>

app/views/mobiles/update.html.erb
<h1>Mobiles#update</h1>
<p>Find me in app/views/mobiles/update.html.erb</p>

app/views/orders/index.html.erb
<html>

<head>

  <title>Mobile Shop</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


  <style>
      body {
          font-family: 'Roboto', sans-serif;
          font-weight: 300;
      }

      header {
          padding: 20px 0;

      }


      footer .row {
          display: flex;
          align-items: center;
      }

      header .row {
          display: flex;
          align-items: center;

      }
      header h1 {
          font-weight: 700;
          margin: 0;
      }

      header nav {
          display: flex;
          justify-content: flex-end;

      }

      header p {
          padding: 0 20px;
          margin: 0;
      }


      .create {
          margin: 40px 0;
      }

      .messages a,
      .create .actions input {
          background-color: #0084d7;
          border: none;
          color: #fff;
          cursor: pointer;
          font-size: 14px;
          margin-top: 10px;
          padding: 12px 24px;
          transition: background-color 0.5s;
          text-decoration: none;
          display: inline-block;
      }



      p.time {
          color: #0084d7;
          font-size: 12px;
          margin-top: 12px;
      }

      button {
          background-color: #f2580b;
          border: none;
          color: #fff;
          cursor: pointer;
          font-size: 14px;
          margin-top: 10px;
          padding: 12px 24px;
          transition: background-color 0.5s;
      }

      button:hover {
          background-color: #c24609;
          transition: background-color 0.5s;
      }

      form label {
          display: block;
          width: 100%;
      }

      form textarea {
          border: 1px solid gray;
          font-family: 'Roboto', sans-serif;
          font-size: 14px;
          font-weight: 300;
          margin: 20px 0 10px;
          min-height: 100px;
          padding: 16px;
          transition: border 0.5s;
          width: 100%;

      }



      form textarea:focus {
          border: 1px solid #0084d7;
          box-shadow: 0;
          outline: 0;
          transition: border 0.5s;
      }




  </style>
</head>

<body>
<header class="containter">
  <div class="row">
    <h1 class="col-xs-4">Mobile Shop</h1>
    <nav class="col-xs-8 text-right">
      <% if !current_user %>
          <p><%= link_to "Početna", '/' %></p>
          <p><%= link_to "LogIn", '/login' %></p>
          <p><%= link_to "SignUp", '/signup' %></p>


      <% else %>
          <p><%= current_user.email %></p>
          <p><%= link_to "Početna", '/' %></p>
          <p><%= link_to "Logout", logout_path, method: "delete" %> </p>

      <% end %>
      <% if current_user && current_user.admin? %>
          <p><%= link_to "Poruke", 'orders/index' %></p>
          <p><%= link_to "Dodaj", '/mobiles/new' %></p>
      <% end %>
      <% if current_user && current_user.user? %>
          <p><%= link_to "Kontakt", 'orders/new' %></p>
      <% end %>
    </nav>
  </div>
</header>


<div class="create">
  <div class="container">


    <% @orders.each do |f| %>


        <blockquote class="blockquote">
          <p class="mb-0"><%= f.pitanje %></p>
          <footer class="blockquote-footer"><%=f.user%></footer>
          <%= link_to "Delete", delete_order_path(f), :method => :delete %>
        </blockquote>

    <% end %>
  </div>
</div>


</body>


</html>

app/views/orders/new.html.erb
<!DOCTYPE html>
<html>

<head>

  <title>Mobile Shop</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


  <style>
      body {
          font-family: 'Roboto', sans-serif;
          font-weight: 300;
      }

      header {
          padding: 20px 0;

      }


      footer .row {
          display: flex;
          align-items: center;
      }

      header .row {
          display: flex;
          align-items: center;

      }
      header h1 {
          font-weight: 700;
          margin: 0;
      }

      header nav {
          display: flex;
          justify-content: flex-end;

      }

      header p {
          padding: 0 20px;
          margin: 0;
      }


      .create {
          margin: 40px 0;
      }

      .messages a,
      .create .actions input {
          background-color: #0084d7;
          border: none;
          color: #fff;
          cursor: pointer;
          font-size: 14px;
          margin-top: 10px;
          padding: 12px 24px;
          transition: background-color 0.5s;
          text-decoration: none;
          display: inline-block;
      }



      p.time {
          color: #0084d7;
          font-size: 12px;
          margin-top: 12px;
      }

      button {
          background-color: #f2580b;
          border: none;
          color: #fff;
          cursor: pointer;
          font-size: 14px;
          margin-top: 10px;
          padding: 12px 24px;
          transition: background-color 0.5s;
      }

      button:hover {
          background-color: #c24609;
          transition: background-color 0.5s;
      }

      form label {
          display: block;
          width: 100%;
      }

      form textarea {
          border: 1px solid gray;
          font-family: 'Roboto', sans-serif;
          font-size: 14px;
          font-weight: 300;
          margin: 20px 0 10px;
          min-height: 100px;
          padding: 16px;
          transition: border 0.5s;
          width: 100%;

      }



      form textarea:focus {
          border: 1px solid #0084d7;
          box-shadow: 0;
          outline: 0;
          transition: border 0.5s;
      }




  </style>
</head>

<body>
<header class="containter">
  <div class="row">
    <h1 class="col-xs-4">Mobile Shop</h1>
    <nav class="col-xs-8 text-right">
      <% if !current_user %>
          <p><%= link_to "Početna", '/' %></p>
          <p><%= link_to "LogIn", '/login' %></p>
          <p><%= link_to "SignUp", '/signup' %></p>


      <% else %>
          <p><%= current_user.email %></p>
          <p><%= link_to "Početna", '/' %></p>
          <p><%= link_to "Logout", logout_path, method: "delete" %> </p>

      <% end %>
      <% if current_user && current_user.admin? %>
          <p><%= link_to "Poruke", 'orders/index' %></p>
          <p><%= link_to "Dodaj", 'mobiles/new' %></p>
      <% end %>
      <% if current_user && current_user.user? %>
          <p><%= link_to "Kontakt", 'orders/new' %></p>
      <% end %>
    </nav>
  </div>
</header>


<div class="create">
  <div class="container">


    <%= form_for(@order) do |f| %>
        <div class="field">

          <p>Email </p>
          <%= f.text_field :user, :value => current_user.email  %><br/>   <br/>

          <p>Pitanje</p>
          <%= f.text_area :pitanje %>

        </div>
        <div class="actions">
          <%= f.submit "Pošalji" %>
        </div>
    <% end %>
  </div>
</div>


</body>


</html>